<?php
/**
 *
 * @Author: jwamser
 * @CreateAt: 5/10/18 8:30 PM
 * Project: FakerExtended
 * File Name: MaterialProvider.php
 */

namespace Fake\Alfred\Provider;

use Faker\Provider\Base;

class Material extends Base
{
    protected static $dryBulkNames = array(
        "Popcorn",
        "Apple Jacks",
        "Oyster Crackers",
        "Cereal",
        "Flaxseed Meal",
        "Iodized Salt",
        "Oatmeal",
        "Potato Flake",
        "Granular Suger",
        "Detergint",
        "Unbleached Flour ",
        "Sunflower Seeds",
        "Nesquik",
        "Dog Food",
        "Lemonade Mix",
        "CakeMix",
        "Elbow Mac",
        "Rice",
        "Brown Sugar",
        "Sea Salt",
        "Pinto Beans",
        "Popcorn Kernals",
        "Powdered Sugar",
        "Niacin (B-3)",
        "Iron",
        "Calcium Sterate",
        "Bun Mix - Full Mix",
        "Corn Starch",
        "Granular Sugar",
        "Whole Wheat Flour",
        "Dicalcium Phosphate",
        "Micro Crystalline Cellulose",
        "Table Salt",
        "Barley Flour",
        "Ribo Flavin",
        "Calcium Sulfate",
        "Sodium Acid Pyrophosphate",
        "Alumina Powder",
        "Silica Flour (Pulverized Sand)",
        "Silica Dioxide ",
        "Ochre",
        "Soy",
        "Hydropropylcecellulose",
        "Sweetened Flake Coconut",
        "Monosodium Glutamate",
        "Aluminum Drops/Drills",
        "Fine Granulat Sugar [51 PCF]",
        "SBS Polymer [21.4 PCF]",
        "Washed KD Salt",
        "Limestone [Calcium Carbonate] 4325 Mesh",
        "Polystyrene Pellets - Magnesium Oxide",
        "Skim Milk [29 PCF]",
        "Intertape Polymers [Bulk Density 0.565 kg/L]",
        "Potato Starch",
        "Nylon w/ Glass Fibers (Ultramid A3HG7 Black Q1720560 )",
        "Silic",
        "Titanium Dioxide - TI02",
        "PVC Resin TI02 - Calcium Carbonate",
        "Animal Blood Plasma",
        " Calcium Chloride [FIBC] (Peladow (R))",
        "Insulation Granules (Microtherm FreeFlowable - Free Pouring Granules of high temperature insalation)",
        "Activated Charcoal 12X40 Mesh",
        "Fartafil - Carbon Fiber",
        "Panex - Milled Carbon Fiber",
        "Decabromodiphenyl Oxide DE83",
        "Irganox 1010",
        "Plastic Regrind",
        "Vinyfor AC_1 Azodicarbonamide",
        "Brewers Yeast BGY40",
        "Soy Flour",
        "Calcium Carbonate G260",
        "Calcium Carbonate G2",
        "Calcium Carbonate G35T",
        "Pulverized Limestone - Mineral Filler",
        "Add - Frit, Brosilicate - 40 Mesh",
        "Alumina, Calc, STD Grade -325 Mesh",
        "Alumina, Fused Brown -30 Mesh",
        "Alumina, Fused Brown(CH) -10 + 30 Mesh",
        "Alumina, Hydrated,C-33 ",
        "Alumina, Reactive GRP 4 1/2 Micron",
        "Alumina, Reactive, Grp 5 3.5 Micron",
        "Alumina, Tabular - 48 Mesh",
        "Alumina, Tabular -325 Mesh",
        "Bauxite, Guyana RASC -6+16 Mesh",
        "Bauxite, Guyana Rasc - 200 Mesh",
        "Bauxite, Guyana Rasc -16 Mesh",
        "Bauxite, Guyana RASC -3+6 Mesh",
        "Bauxite, Northern Chinese -16 Mesh",
        "Bauxite, Northern Chinese -3/4+4 Mesh",
        "Bauxite, Northern Chinese -3+6 Mesh",
        "Bauxite, Northern Chinese -6+16 Mesh",
        "Cement, 70%, SECAR 71",
        "Clay, 631-FE, Calc MED FE -1/2+4 Mesh",
        "Clay, 631-FE, Calc MED FE -20 Mesh",
        "Clay, 631-FE, Calc MED FE -3+4 Mesh",
        "Clay, 631-FE,Calc Med FE -4 +8 Mesh",
        "Clay, 631-FE,Calc MED FE -8+20 Mesh",
        "Fireclay, Raw, Bentonite - 200 Mesh",
        "FireClay, Raw, Bond Gleason Ball Clay",
        "Fireclay, Raw, Bond Gleason Ball Clay",
        "Fireclay, Raw, Bond M&D Ball Clay",
        "Fireclay, Raw, Bond TN#6",
        "Mullite, 47% AL203 M47 - 200 Mesh",
        "Mullite, 47% AL203 M47 -4 +8 Mesh",
        "Mullite, 47% AL203 M47 -8+20 Mesh",
        "Mullite, 60% Al203 M60 -16 Mesh",
        "Mullite, 60% Al203 M60 -200 Mesh",
        "Mullite, 60% Al203 M60 -3 +6 Mesh",
        "Mullite, 60% AL203 M60 -6+16 Mesh",
        "Mullite, Andalusite - 18 Mesh, Randalusite",
        "Mullite, Andalusite - 7 + 18 Mesh Randalusite",
        "Mullite, Raw Kyanite -100 Mesh",
        "Mullite, Raw Kyanite -100 Mesh",
        "Mullite, raw kyanite -48 mesh ",
        "Silica, Fume Undensified <20 PCF",
        "Silica, Fume, Densified",
        "Silica, Potters Flint - 200 Mesh",
        "Silica, Sand, Ground -28 Mesh",
        "Silicon Carbide 96% GRF - 100 Mesh",
        "Silicon Carbide, #1 Grd -200 Mesh",
        "Zircon, Sand Prime Grade -65 Mesh Granular",
        "Magnesite 33, -200 Mesh",
        "Feldspar (Minspar 200)",
        "Ceramic frit 608",
        "Ceramic Frit 2425",
        "Ceramic Frit F110/A",
        "Calcined Alumina",
        "Ball Clay ( ottcc No. 1)",
        "Premiere CT Ball Clay",
        "Zinc Oxide (Kaolin)",
        "Zirconium Silicate",
        "Cocao Powder",
        "Petroleum Coke",
        "Goat Pellets (Feed)",
        "UVASORB (HA88 FD)",
        "Solumer (851T)",
        "Wall Board",
    );

    /**
     * A random Material name.
     * @return string
     */
    public function materialName()
    {
        return static::randomElement(static::$dryBulkNames);
    }
}